trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo API Gateway test!
  displayName: 'Run a one-line script'
- script: 'sudo npm install -g newman'
  workingDirectory: '$(System.DefaultWorkingDirectory)'
  displayName: 'Install the New man collection for curling'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/projects/petstore'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
    verbose: true