trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
 - stage: "BuildAndDeploy"
   jobs:
     - job : "BuildAndDeployAPIsToAPIGateway"
       steps:
         - script: 'sudo npm install -g newman'
           workingDirectory: '$(System.DefaultWorkingDirectory)'
           displayName: 'Prerequisite'
         - task: ArchiveFiles@2
           inputs:
            rootFolderOrFile: '$(System.DefaultWorkingDirectory)/projects/petstore'
            includeRootFolder: false
            archiveType: 'zip'
            archiveFile: '$(System.DefaultWorkingDirectory)/postman/import/$(Build.BuildId).zip'
            replaceExistingArchive: true
            verbose: true
           displayName: 'Create the API Deployable from the flat representation'
         - script: 'newman run import/ImportAPI.json  --reporters cli --env-var file_Loc=import/$(Build.BuildId).zip -e qa_environment.json'
           workingDirectory: '$(System.DefaultWorkingDirectory)/postman'
           displayName: 'Import the Deployable To API Gateway'      
         - publish :  '$(System.DefaultWorkingDirectory)/postman/import/$(Build.BuildId).zip'
 - stage: "Test"
   jobs:
     - job: "RunAPIInvokeTests"
       steps:
        - script: 'sudo npm install -g newman'
          workingDirectory: '$(System.DefaultWorkingDirectory)'
          displayName: 'Prerequisite'
        - script: 'newman run api/APITest.json  --reporters cli,junit --reporter-junit-export Results/junitReport.xml -e qa_environment.json'
          workingDirectory: '$(System.DefaultWorkingDirectory)/postman'
          displayName: 'Run tests on the QA Machine'
          continueOnError: true
        - task: PublishBuildArtifacts@1
          inputs:
            pathToPublish: '$(System.DefaultWorkingDirectory)/postman/Results/junitReport.xml'
            artifactName: report
     - job: "RunPerformanceTests"
       steps:
         - script: 'echo Running performance Tests'
 - stage: "Report"
   jobs:
     - job: "PublishReport"
       steps:
        - task: DownloadBuildArtifacts@0
          inputs:
            buildType: 'current'
            downloadType: 'single'
            artifactName: 'report'
            downloadPath: '$(System.DefaultWorkingDirectory)'
        - task: PublishTestResults@2
          inputs:
            testResultsFormat: 'JUnit'
            testResultsFiles: '$(System.DefaultWorkingDirectory)/report/*.xml'
            testRunTitle: 'QA environment test failures'
            publishRunAttachments: false
 - stage: "Rollout"
   condition: succeeded('Test')
   jobs:
     - job: "PromoteToProd"
       steps:
        - script: 'sudo npm install -g newman'
          workingDirectory: '$(System.DefaultWorkingDirectory)'
          displayName: 'Prerequisite'
        - script: 'newman run promotion/PromotionManagement.json  --reporters cli -g qa_environment.json -e $(System.DefaultWorkingDirectory)/projects/petstore/promotion_payload.json --env-var buildNumber=\"$(Build.BuildId)\"'
          workingDirectory: '$(System.DefaultWorkingDirectory)/postman'
          displayName: 'Promotion'
