trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
 - stage: "Build"
   jobs:
     - job: "CreateAPIDeployable"
       steps:
         - task: ArchiveFiles@2
           inputs:
            rootFolderOrFile: '$(System.DefaultWorkingDirectory)/projects/petstore'
            includeRootFolder: false
            archiveType: 'zip'
            archiveFile: '$(System.DefaultWorkingDirectory)/postman/import/$(Build.BuildId).zip'
            replaceExistingArchive: true
            verbose: true
           displayName: 'Create the API Deployable from the flat representation'
         - publish: '$(System.DefaultWorkingDirectory)/postman/import/$(Build.BuildId).zip'
           artifact: APIDeployable.zip
           displayName: 'Publish the created API Deployable'
 - stage: "Deploy"
   jobs:
     - job : "DeployDeployableToAPIGateway"
       steps:
         - script: 'sudo npm install -g newman'
           workingDirectory: '$(System.DefaultWorkingDirectory)'
           displayName: 'Prerequisite'
         - download: current
           artifact: APIDeployable.zip
         - script: 'newman run import/ImportAPI.json  --reporters cli --env-var file_Loc="$(Pipeline.Workspace)/APIDeployable.zip" -e qa_environment.json'
           workingDirectory: '$(System.DefaultWorkingDirectory)/postman'
           displayName: 'Import the API To API Gateway'      
 - stage: "Test"
   jobs:
     - job: "RunAPIInvokeTests"
       steps:
        - script: 'sudo npm install -g newman'
          workingDirectory: '$(System.DefaultWorkingDirectory)'
          displayName: 'Prerequisite'
        - script: 'newman run api/APITest.json  --reporters cli,junit --reporter-junit-export Results/junitReport.xml -e qa_environment.json'
          workingDirectory: '$(System.DefaultWorkingDirectory)/postman'
          displayName: 'Run tests on the QA Machine'
          continueOnError: true
        - publish :  '$(System.DefaultWorkingDirectory)/postman/Results/junitReport.xml'
          artifact: UnitTestResult.xml
     - job: "RunPerformanceTests"
       steps:
         - script: 'echo Running performance Tests'
 - stage: "Report"
   jobs:
     - job: "PublishReport"
       steps:
        - download: current
          artifact: UnitTestResult.xml
        - task: PublishTestResults@2
          inputs:
            testResultsFormat: 'JUnit'
            testResultsFiles: '$(Pipeline.Workspace)/*.xml'
            testRunTitle: 'QA environment test failures'
            publishRunAttachments: false
 - stage: "Rollout"
   condition: succeeded('Test')
   jobs:
     - job: "MergeDevelopToMaster"
       steps:
        - task: CreatePullRequest@1
          inputs:
            repoType: 'GitHub'
            githubEndpoint: 'przemekulik'
            sourceBranch: 'develop'
            targetBranch: 'master'
            title: 'Merge develop to master'
       
       
